---

#  ansible-galaxy role install geerlingguy.docker --force
- name: "include_role geerlingguy.docker"
  ansible.builtin.include_role:
    name: geerlingguy.docker
  when: ansible_architecture != 'armv7l'
  vars:
    docker_edition: 'ce'
    docker_users: []
  tags:
    - docker
    - geerlingguy_docker

- name: "include_role geerlingguy.docker_arm"
  ansible.builtin.include_role:
    name: geerlingguy.docker_arm
  when: ansible_architecture == 'armv7l'
  vars:
    docker_users: []
  tags:
    - docker
    - geerlingguy_docker

- name: pip install docker module  # noqa: package-latest
  ansible.builtin.pip:
    name:
      - docker
    state: latest

# TODO: auto detect unit file to support different OS (sample /lib/systemd/system/docker.service on Ubuntu)
- name: "create directory for systemd override for docker.service"
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0775'
    owner: root

- name: "place systemd override for docker.service"
  ansible.builtin.copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Unit]
      After=network-online.target firewalld.service containerd.service remote-fs.target
      Requires=docker.socket containerd.service remote-fs.target
    mode: '0644'
  register: _place_override_file

- name: reload systemd configuration  # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: _place_override_file.changed | bool
  tags:
    - docker
    - docker_systemd

- name: docker | create docker network
  community.general.docker_network:
    name: "{{ docker_network_name }}"
    appends: true
    # scope: "local"
    driver: 'bridge'
    driver_options: {com.docker.network.bridge.name: "{{ docker_network_device_name }}"}
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"
        gateway: "{{ docker_network_gateway }}"
        iprange: "{{ docker_network_iprange | default(omit) }}"
        aux_addresses: "{{ docker_network_aux_addresses | default(omit) }}"
        #  host1: 172.3.27.3
        #  host2: 172.3.27.4
    state: present
  when: docker_networks | length > 0
  tags:
    - docker
    - docker_network

# - name: "collect facts about system services (firewalld)"
#   ansible.builtin.service_facts:
#   register: services_state

# - name: Debug
#   ansible.builtin.debug:
#     var: services_state.ansible_facts.services['firewalld.service'].state
#   when:
#     - services_state.ansible_facts.services['firewalld.service'].state is defined
#     - services_state.ansible_facts.services['firewalld.service'].state == "running"
#     - ansible_os_family == "RedHat"

# - name: docker | add network interface docker0 to trusted networks
#   ansible.posix.firewalld:
#     zone: trusted
#     interface: docker0
#     immediate: yes
#     permanent: yes
#     state: enabled
#   when:
#     - services_state.ansible_facts.services['firewalld.service'].state is defined
#     - services_state.ansible_facts.services['firewalld.service'].state == "running"
#     - ansible_os_family == "RedHat"
